### ISSUE TITLE
scan usearch identity for match with BLAST clustering

### ISSUE THREAD

**Issue by joelb123** [legumeinfo/azulejo#193]
Using the histograms in #191, scan identity values in usearch clustering to identify the value with closest match to those produced by dagchainer_tool with default parameters.  Present results in a way that go/no-go decision can be made for using usearch for homology clustering for now.  Document the results.

**Comment by adf-ncgr** [comment]
@joelb123 I set this as highest priority since I believe you had said it was likely the most direct path to getting a result for the glycine 33 that will be most similar to a scaled-up version of what you produced for the 7. But, if you can give me an estimate for how long you think it will be before we are ready to make a decision on usearch, based on that I might ask you to go ahead and get homology results for the 33 via the "dagchainer_tool with default parameters" (aka BLAST on cds). Whichever gives us the fastest path to deciding whether the synteny algorithm will work effectively on the 33 should be fine with me- but let me know what you think I can expect as a timeline on the issue as you've formulated it and we can discuss further.

**Comment by joelb123** [comment]
Scan done; matches are not good at any identity level.  Comparison on glycine7,  where nucleic-acid-space BLAST with 95% identity puts about 70% into matches of size 7 and less than 2% of matches into pairs showed that usearch put as most 42~ into the size-7 matches and 20% into size-2 matches.  

I suspect this is because of usearch's internal criteria refusing to recognize some matches as alignable, resulting in splitting into sets of 2 and 3 instead of the full set of 7.
